# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bellhops < Formula
  desc ""
  homepage "https://github.com/bellhops/homebrew-bellhops"
  version "1.0.11"

  on_macos do
    url "https://github.com/bellhops/tfc-cli/releases/download/v1.0.11/tfc-cli_1.0.11_darwin_all.tar.gz"
    sha256 "a788dd9082d0b14563afd92e0a293bd99fb44d92cdf454ee857aa07c937cca7d"

    def install
      bin.install "tfc-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bellhops/tfc-cli/releases/download/v1.0.11/tfc-cli_1.0.11_linux_arm64.tar.gz"
      sha256 "a22bf2ec30a3ab7ba80dc1079d0cdd5686122fd855a305512c36f3909c9bdefc"

      def install
        bin.install "tfc-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bellhops/tfc-cli/releases/download/v1.0.11/tfc-cli_1.0.11_linux_amd64.tar.gz"
      sha256 "8dac3f3f9cc330e7bef2020ca99df08ebe8b068baf1f5b805b5964f0c35c75ec"

      def install
        bin.install "tfc-cli"
      end
    end
  end
end
