# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfcCli < Formula
  desc ""
  homepage "https://github.com/bellhops/homebrew-bellhops"
  version "1.0.12"

  on_macos do
    url "https://github.com/bellhops/tfc-cli/releases/download/v1.0.12/tfc-cli_1.0.12_darwin_all.tar.gz"
    sha256 "02576f64965110a58ff11ac3be28833c9878b8cc094f13ba74aab06247bf4077"

    def install
      bin.install "tfc-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bellhops/tfc-cli/releases/download/v1.0.12/tfc-cli_1.0.12_linux_arm64.tar.gz"
      sha256 "5a1c1cc4c3f8ad5db00978cd7714e327d2b53f1bfbd0b8f82f00692a4f683ca5"

      def install
        bin.install "tfc-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bellhops/tfc-cli/releases/download/v1.0.12/tfc-cli_1.0.12_linux_amd64.tar.gz"
      sha256 "5aa35f7d7185eab1564be7c9b8ae9c0541a3cc258b7dc03fb4eff4c2e3b66c2b"

      def install
        bin.install "tfc-cli"
      end
    end
  end
end
